config/routes.rb
Rails.application.routes.draw do
  resources :amigos, except: :show

  root 'amigos#index'
  get '/partners' => 'amigos#partners'
end

app/models/amigo.rb
class Amigo < ActiveRecord::Base
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/amigos_controller.rb
class AmigosController < ApplicationController
  before_action :set_amigo, only: [:show, :edit, :update, :destroy]

  # GET /amigos
  # GET /amigos.json
  def index
    @amigos = Amigo.all.reverse_order
  end

  def partners
    @amigos = Amigo.all.reverse_order
  end

  # GET /amigos/1
  # GET /amigos/1.json
  def show
  end

  # GET /amigos/new
  def new
    @amigo = Amigo.new
  end

  # GET /amigos/1/edit
  def edit
  end

  # POST /amigos
  # POST /amigos.json
  def create
    @amigo = Amigo.new(amigo_params)

    respond_to do |format|
      if @amigo.save
        format.html { redirect_to amigos_path, notice: 'Amigo was successfully created.' }
        format.json { render :show, status: :created, location: @amigo }
      else
        format.html { render :new }
        format.json { render json: @amigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amigos/1
  # PATCH/PUT /amigos/1.json
  def update
    respond_to do |format|
      if @amigo.update(amigo_params)
        format.html { redirect_to amigos_path, notice: 'Amigo was successfully updated.' }
        format.json { render :show, status: :ok, location: @amigo }
      else
        format.html { render :edit }
        format.json { render json: @amigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amigos/1
  # DELETE /amigos/1.json
  def destroy
    @amigo.destroy
    respond_to do |format|
      format.html { redirect_to amigos_url, notice: 'Amigo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amigo
      @amigo = Amigo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amigo_params
      params.require(:amigo).permit(:nomeCompleto, :telefone)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amigos/_form.html.haml
= form_for(@amigo) do |f|
  - if @amigo.errors.any?
    #error_explanation
      %h2
        = pluralize(@amigo.errors.count, "error")
        prohibited this amigo from being saved:
      %ul
        - @amigo.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label 'Nome'
    %br/
    = f.text_field :nomeCompleto, class:"form-control"
  .actions
    - if @amigo.nomeCompleto
      = f.submit 'Atualizar', class: 'col btn btn-info btn-lg'
    - else
      = f.submit 'Adicionar', class: 'col btn btn-info btn-lg'

app/views/amigos/edit.html.haml
.text-center.col-lg-12.mt-4
  %h1.lead.col-xs-12.mb-0 Amigo Secreto
  %small.col-lg-12 OS FILHOS DE HONÓRIO
.col-12.mt-4.d-flex.justify-content-center
  .col-lg-6.d-none.d-lg-block.card
    = image_tag 'family.jpg', class: 'mt-2 img-fluid img-thumbnail'
    .card-body
      %h4.lead O amigo secreto da família acontecerá no dia 24 de Dezembro de 2020, na casa da Dona Maria e do Seu Antônio Honório.
  .col-lg-6
    = link_to amigos_path do
      =icon('fas', 'chevron-left')
    .list-group.col-lg-6.col-xs-12
      = render 'form'
      %br

app/views/amigos/index.html.haml
.text-center.col-lg-12.mt-4
  %h1.lead.col-xs-12.mb-0 Amigo Secreto
  %small.col-lg-12 OS FILHOS DE HONÓRIO
.col-12.mt-4.d-flex.justify-content-center
  .col-lg-6.d-none.d-lg-block.card
    = image_tag 'family.jpg', class: 'mt-2 img-fluid img-thumbnail'
    .card-body
      %h4.lead O amigo secreto da família acontecerá no dia 24 de Dezembro de 2020, na casa da Dona Maria e do Seu Antônio Honório.
  .col-lg-6
    %table.table.table-striped.table-sm
      %thead
        %tr
          %th.text-left
            %b Amigo Secreto
          %th
      %tbody
        - @amigos.each do |amigo|
          %tr
            %td.text-left= amigo.nomeCompleto       
            %td
              = link_to edit_amigo_path(amigo) do
                = icon('fas', 'edit text-success')
              = link_to amigo_path(amigo), method: :delete, data: { confirm: 'Tem certeza que quer desistir?' } do
                =icon('fas', 'times text-danger')
    
    = link_to 'Adicionar Amigo', new_amigo_path, class: 'lead btn btn-info btn-lg'

app/views/amigos/new.html.haml
.text-center.col-lg-12.mt-4
  %h1.lead.col-xs-12.mb-0 Amigo Secreto
  %small.col-lg-12 OS FILHOS DE HONÓRIO
.col-12.mt-4.d-flex.justify-content-center
  .col-lg-6.d-none.d-lg-block.card
    = image_tag 'family.jpg', class: 'mt-2 img-fluid img-thumbnail'
    .card-body
      %h4.lead O amigo secreto da família acontecerá no dia 24 de Dezembro de 2020, na casa da Dona Maria e do Seu Antônio Honório.
  .col-lg-6
    = link_to amigos_path do
      =icon('fas', 'chevron-left')
    .list-group.col-lg-6.col-xs-12
      = render 'form'
      %br

app/views/amigos/partners.haml
- @amigos.each do |amigo|
  = amigo.nomeCompleto
  %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>SecretSanta</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>